#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build test

permissions: write-all
# 开启写权限，防止无法上传到release

on:
  workflow_dispatch:
    inputs:
      USE_NX30PRO_EEPROM:
        description: 'Use nx30pro eeprom'
        required: true
        default: true
        type: boolean
      USE_52MHZ:
        description: 'Use 52MHz max-frequency'
        required: true
        default: false
        type: boolean

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  FREE_DISK_SH: scripts/free_disk_space.sh
  ENV_SH: scripts/environment.sh
  DIY1_SH: scripts/diy1.sh
  DIY2_SH: scripts/diy2.sh
  CLASH_CORE: scripts/preset-clash-core.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查
       run: |
        uname -m
        lsb_release -a
        uname -r
